name: json_string
description: A simple JSON utility package for Dart and Flutter.
version: 0.0.1
#author: Daniele Paradiso <email>
homepage: https://github.com/parsodyl/json_string

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.5.0
