name: json_string
description: A simple and lightweight JSON data container for Dart and Flutter.
version: 1.1.0
author: Daniele Paradiso <parsodyl@gmail.com>
homepage: https://github.com/parsodyl/json_string

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_util: ^0.3.0

dev_dependencies:
  test: ^1.5.1
