name: json_string
description: A simple and lightweight JSON data container for Dart and Flutter.
version: 3.0.1
homepage: https://github.com/parsodyl/json_string

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_util: ^2.0.0

dev_dependencies:
  test: ^1.17.12
  pedantic: ^1.9.0
